export default {
    container: {
        flex: 1,
        height: '100%',
        backgroundColor: '#fff',
        // alignItems: 'center',
        // justifyContent: 'center',
        // width: '100%',
    },
    item: {
        flex: 1,
        backgroundColor: '#01C38E',
        height: 200,
        marginVertical: 11,
        marginHorizontal: 7,
        padding: 2,
        borderWidth: 2,
        borderColor: '#01C38E',
        borderRadius: 6,
        shadowColor: '#171717',
        shadowOffset: { width: 2, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 3,
    },
    itemImg: {
        width: '100%',
        height: '75%',
        borderRadius: 6,
        // marginVertical: 10,

    },
    itemText: {
        height: '25%',
        // width: '100%',
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 30,
        textAlign: 'center',
        paddingVertical: 8,
    },
    title: {
        fontSize: 32,
    },
    input: {
        height: 40,
        margin: 12,
        borderWidth: 1,
        padding: 10,
    },
    containerDate: {
        flexDirection: 'row',
    },
    date: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '40%',
        // backgroundColor: 'red',
    },
    textDate: {
        // alignItems: 'center',
        // justifyContent: 'center',
        height: 40,
        margin: 12,
        fontSize: 20,
        // borderWidth: 1,
        padding: 10,
        width: '30%',
        // backgroundColor: 'red',
    },
    picker: {
        // flex: 1,
        fontSize: 25,
        alignItems: 'center',
        textAlign: 'center',
        // justifyContent: 'center',
        // backgroundColor: 'red',
    }
}